language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
install:
  - yarn install
before_script:
  - yarn compile
script:
  - yarn coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    skip_cleanup: true
    email: code@tommilligan.net
    api_key: $NPM_API_KEY
    on:
      branch: master
      tags: true
      condition: $TRAVIS_NODE_VERSION = 7
notifications:
  email: false
